Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"

  # - - -[Server] - - -
  config.vm.define "balbeckeS" do |server|
    server.vm.hostname = "balbeckeS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "balbeckeS"
      vb.cpus = 4
      vb.memory = 2048
      # vb.gui = true # Lance avec l'UI pour debugg
    end
    server.vm.provision "shell", path: "scripts/install_K3s_controller_mode.sh"
  end


end
