apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app # matchLabels for argocd
  template:
    metadata:
      labels:
        app: iot-app # Label pour argocd
    spec:
      containers:
        - name: iot-app
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: iot-app
  namespace: dev
spec:
  type: NodePort
  selector:
    app: iot-app # matchLabels pour argocd
    # app.kubernetes.io/name: iot-app
  ports:
    - port: 8888              # Port listen by the app 
      targetPort: 8888        # internal Port in the container
      nodePort: 30042         # external cluster Port, The range of valid ports is 30000-32767
      